### PR TITLE
Best practices of using resources in code

### PR DESCRIPTION
**Pull request by vadymmarkov**
Related to https://github.com/hyperoslo/iOS-playbook/issues/145

### CODE REVIEW

**Comment by 3lvis** [comment]
If it's only related to Swift, it should go in `style-guidelines/swift`. Best practices is only for things that apply to both languages.

**Comment by vadymmarkov** [comment]
@3lvis :wink: Moved to `style-guidelines/swift`

**Comment by fespinoza** [comment]
maybe a dumb question (since I barely know the language) but i think this kind of stuff would be an enumerate instead?

then in some cases you need to do a `switch` you would get help from the compiler to handle all the cases

**Comment by 3lvis** [comment]
@fespinoza This is for resoruces, like fonts and colors, we don't need a `switch` for that.

**Comment by zenangst** [comment]
I like this!

**Pull request merged**
