### PR TITLE
Improve use of self

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by zenangst** [comment]
I agree with this change :beers:

**Comment by 3lvis** [comment]
I agree!

**Comment by zenangst** [comment]
salute

**Comment by kostiakoval** [comment]
update use example than.

**Comment by 3lvis** [comment]
@kostiakoval The example doesn't complain the guidelines? I think they do.

**Comment by kostiakoval** [comment]
nope.
"and when referencing properties:" vs "when referencing properties in closure expressions (as required by the compiler):"
The example is sowing referencing property from closure.

**Comment by 3lvis** [comment]
I didn't meant that, I meant `and when referencing properties` not only in closures.

**Comment by jgorset** [comment]
It's unclear to me whether we should prefix with `self` when referencing properties that don't clash with arguments. For example:

```swift
class BoardLocation {
  let row: Int, column: Int, foo: Int

  init(row: Int, column: Int) {
    self.row = row
    self.column = column

    let closure = {
      println(self.row)
    }
  }

  func randomFoo() {
    foo = "So random!"
  }
}
```

**Comment by jgorset** [comment]
For the record I'm :+1: on dropping `self` unless strictly necessary (mostly because that's the convention in Ruby), but I don't feel too strongly about it.

**Comment by kostiakoval** [comment]
@jgorset :heart_eyes: :hand: I'm for draping `self` as well

**Comment by 3lvis** [comment]
If `self` weren't need in all cases I would be in favor of dropping them, I just want to avoid inconsistency.

The problem is that using `self.` for me has a higher purpose that just making the compiler friendly, is a way to indicate that the scope of this variable goes beyond a closure or a function.

**Comment by jgorset** [comment]
I agree with your argument on consistency, and I remember considering to go back and prefix everything with `self` when I realized I needed it in closures anyway.

I also think your argument on indicating scope is the reason why it's not possible to _assign_ to instance variables without prefixing with `self` in Ruby, although _referencing_ is possible without it. I think most Rubyists feel fine about _referencing_ instance variables because you can clearly see that it's not set anywhere in the local scope, though the brevity of it comes at the expense of consistency.

**Comment by kostiakoval** [comment]
the question is Why apple has added it? why both github and reywenderwich suggest using it?
`self` is not needed in almost all cases. 1 cause you must sue it - when reference it in a closure.
Swift is about being clear (clear intention about the code, what it does) 


```
self.items = fetchItems()
items = fetchItems()
```

**Comment by 3lvis** [comment]
Is not that you'll have to make a lot of work and type a lot extra, the ideal scenario is anyway keep as least global variables as possible.

[Look the amount of global variables (properties) that we have in Sync](https://github.com/hyperoslo/Sync/blob/master/Source/Sync.m): 0

**Comment by RamonGilabert** [comment]
I agree with @3lvis about using self to point to a variable that can be use through all the class. Shouldn't all the constants you are declaring with let be a var instead?

**Comment by 3lvis** [comment]
>Swift is about being clear (clear intention about the code, what it does)

I don't see why this is more clear:
```swift
items = fetchItems()
```

Than this:
```swift
self.items = fetchItems()
```

**Comment by zenangst** [comment]
@3lvis For me, the second one is more clear.
Imagine that you are viewing a change set on GitHub, without `self`, you don't know that this is an instance property.

**Comment by jgorset** [comment]
But do you care whether it's an instance property?

**Comment by RamonGilabert** [comment]
I see the second one more clear, the first one could reference to a variable within the method or the function, so self is better for me in that case!

**Comment by jgorset** [comment]
You could argue that's an implementation detail rather than what the code actually accomplishes.

**Comment by zenangst** [comment]
@jgorset it could impact the change that you are looking at. Is it a global or a local change.

**Comment by jgorset** [comment]
It's a fine line, but I guess the reason why you're not _required_ to prefix with `self` in Ruby or Swift is the same reason that you're not required to use paranthesis or curly braces or semicolons in Ruby. You just don't need to read that to figure out what the code is meant to accomplish.

**Comment by jgorset** [comment]
Then again paranthesis and curly braces and semicolons add _nothing_, whereas `self` actually does something to describe what the code does (albeit less than the rest of it).

**Comment by zenangst** [comment]
It implies `scope`.

**Comment by jgorset** [comment]
Yep. Which is why I'm so torn on this one.

**Comment by jgorset** [comment]
Great discussion, by the way, I like you guys.

**Comment by RamonGilabert** [comment]
I still feel the constants should change into var's. I guess it's not a necessary thing to add, but it makes to me the code more readable.

**Comment by jgorset** [comment]
If you don't intend to change the value of the properties, constants are more lightweight than variables, no?

**Comment by kostiakoval** [comment]
> I still feel the constants should change into var's

Never ever ever ever! No just no.

**Comment by zenangst** [comment]
@RamonGilabert are you on drugs?

**Comment by 3lvis** [comment]
@kostiakoval @RamonGilabert constants vs variables seem like a different discussion, do you mind opening a separate issue for that?

**Comment by jgorset** [comment]
YEAH @RamonGilabert WHY WOULD YOU EVEN SAY THAT

**Comment by RamonGilabert** [comment]
OMG, right, I'm from my iPad in the library trying to follow the conversation... :(

**Comment by zenangst** [comment]
@jgorset calm down, I think that was the meds taking. @RamonGilabert right, you didn't mean that?

**Comment by jgorset** [comment]
I AM CALM

**Comment by kostiakoval** [comment]
:D

**Comment by 3lvis** [comment]
So base that @jgorset is torn, I give him: 0.5 on YES MERGE THIS.

YES MERGE THIS: 0.5 (@jgorset) + 1.0 (@zenangst) + 1.0 (@3lvis) + 1.0 (@RamonGilabert)
NOOOOOO: 0.5 (@jgorset) + 1.0 (@kostiakoval)

**Comment by RamonGilabert** [comment]
Jajajajajaja :D I'm going to keep studying ☺️

**Comment by 3lvis** [comment]
@kostiakoval you see what I did there with the 1.0? 

MUAHAHAH

**Comment by zenangst** [comment]
giphy-19

**Comment by jgorset** [comment]
I agree with your math, @3lvis. ;-)

**Comment by kostiakoval** [comment]
math - :+1: 
feelings - :broken_heart:

P.S
just kidding guys ))

**Pull request merged**
