### PR TITLE
Steps to ship a component

### PR DESCRIPTION
**Pull request by 3lvis**
Listed a few things that we did when shipping Form and Sync.

Check the rendered markdown here => https://github.com/hyperoslo/iOS-playbook/blob/improve/steps-to-ship/COMPONENTS.md#steps-to-ship-your-component

### CODE REVIEW

**Comment by RamonGilabert** [comment]
I did it in here, I guess makes more sense than another pull request.

**Comment by 3lvis** [comment]
@RamonGilabert looks good, but you could always make a pull request to this pull request.

**Comment by attila-at-hyper** [comment]
@3lvis I really like this! :+1:

**Comment by zenangst** [comment]
@vadymmarkov any thoughts? :sunglasses:

**Comment by vadymmarkov** [comment]
Do we have this description / explanation of dependencies in any of our Pods?

**Comment by zenangst** [comment]
@vadymmarkov nope I don't think we have that at the moment

**Comment by RamonGilabert** [comment]
But I think it would be nice to add it, at least some links to the dependencies for the users to check what they're installing

**Comment by vadymmarkov** [comment]
Agreed. Overall I like new additions!

**Comment by 3lvis** [comment]
@vadymmarkov @zenangst We have a components section in Sync

https://github.com/hyperoslo/Sync#components

**Pull request merged**
