### PR TITLE
Use { even if it's one line for if statements

### PR DESCRIPTION
**Pull request by NSElvis**

### CODE REVIEW

**Comment by timkurvers** [comment]
:+1: x 1000

**Comment by kostiakoval** [comment]
:+1: x 1000000000

**Comment by kostiakoval** [comment]
in Swift it's required! no way around

**Comment by NSElvis** [comment]
@kostiakoval merge? :dancers:

**Comment by kostiakoval** [comment]
I don't feel confident to merge some stuff to Hyper-style guide. I mean I'm not a core/hyper dev

**Comment by NSElvis** [comment]
@kostiakoval you are otherwise you wouldn't have the merge button

**Comment by kostiakoval** [comment]
))) thanks

**Pull request merged**
