### PR TITLE
Add paragraph and example about generic naming

### PR DESCRIPTION
**Pull request by zenangst**

### CODE REVIEW

**Comment by kostiakoval** [comment]
close  #53

**Comment by NSElvis** [comment]
yes-yes-yes-o

**Comment by NSElvis** [comment]
@zenangst @kostiakoval might be better to have it in https://github.com/hyperoslo/iOS-playbook/blob/master/BEST_PRACTICES.md ?

**Comment by NSElvis** [comment]
@zenangst @kostiakoval https://github.com/hyperoslo/iOS-playbook/pull/54

**Comment by zenangst** [comment]
Maybe, but I think it might be good to mention it as a generic thing. I don't see this as something unique for Core Data.

**Comment by zenangst** [comment]
But we might have to change the paragraph around a bit to not have any mention of Core Data, what do you guys think?

**Pull request merged**
