### PR TITLE
Update RESOURCES with Mostly Adequate Guide to Functional Programming in JavaScript

### PR DESCRIPTION
**Pull request by onmyway133**
This is simply the best explanation I found so far :notes:

### CODE REVIEW

**Comment by vadymmarkov** [comment]
Not a big fun of JS, but its out of the context :smile: The book seems nice in terms of introduction to functional programming. What do you think @hyperoslo/ios ?

**Comment by zenangst** [comment]
I like it! :+1:

**Comment by vadymmarkov** [comment]
I'll just go and merge this, because why not 😄

**Comment by onmyway133** [comment]
👍

**Comment by onmyway133** [comment]
Oh, I did submit a JS resource 2 years ago 🙄

**Pull request merged**
