### PR TITLE
Improve Example definition

### PR DESCRIPTION
**Pull request by 3lvis**
- [x] Improve Example definition
- [x] Update document title
- [x] Remove missing indexes

### CODE REVIEW

**Comment by 3lvis** [comment]
walter-sobchacks-caring-rules-outburst-reaction-gif-in-big-lebowski

**Comment by zenangst** [comment]
@3lvis :+1:

**Comment by 3lvis** [comment]
>GitHub has very smart example and explanation when to use structs and classes 
https://github.com/github/swift-style-guide#prefer-structs-over-classes

— @kostiakoval

**Comment by 3lvis** [comment]
@kostiakoval: I still feel that the example we give is clearer, they don't say why using structs is "better" they just show that you could also use structs.

**Comment by kostiakoval** [comment]
Struct vs classes is very complex topic. saying use classes for things that have identity does sounds right. I would leave it more open for discussion.

example from Raywenderlich is ob because it's more for mass-use (for many readers). but githus once feels more for "true-dev-masters" and we are "true-dev-masters" (rock)

They are not showing why it's better because the know that. They are saying a rule - Do that! 
> Unless you require functionality that can only be provided by a class (like identity or deinitializers), implement a struct instead.

**Comment by 3lvis** [comment]
I'm more a Raywenderlich type of guy but I understand your point. In any case I would rather just have this:

```
Unless you require functionality that can only be provided by a class (like identity or deinitializers), implement a struct instead.
```

I don't see the point on their code example.

**Comment by 3lvis** [comment]
@kostiakoval regarding the structs vs classes part https://github.com/hyperoslo/iOS-playbook/pull/99

**Pull request merged**
