### PR TITLE
Update code styles

### PR DESCRIPTION
**Pull request by zenangst**

### CODE REVIEW

**Comment by 3lvis** [comment]
I think we already have this in the code style guidelines.

**Comment by 3lvis** [comment]
Maybe we can improve it there.

**Comment by zenangst** [comment]
But should this be a code style? This is more how to configure the project?

**Comment by zenangst** [comment]
Oh right, I see now.

**Comment by zenangst** [comment]
I'll fix it!

**Comment by zenangst** [comment]
@hyperoslo/ios what do you think?

**Comment by markvaldy** [comment]
Looks good.

**Pull request merged**
