### PR TITLE
Simplify Classes and Structs section

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by zenangst** [comment]
:red_circle: :wedding:

**Comment by kostiakoval** [comment]
:red_circle: :wedding: What does that means ? ???

**Comment by zenangst** [comment]
spoiler

**Comment by 3lvis** [comment]
@kostiakoval (Game of Thrones) Spoiler alert http://gameofthrones.wikia.com/wiki/Red_Wedding

**Pull request merged**
