### PR TITLE
Add paragraph on plugin compatibility

### PR DESCRIPTION
**Pull request by attila-at-hyper**

### CODE REVIEW

**Comment by 3lvis** [comment]
@attila-at-hyper https://github.com/hyperoslo/iOS-playbook/pull/107

**Comment by 3lvis** [comment]
@attila-at-hyper My PR pointed to your branch, this still hasn't been merged. :grin:

**Comment by attila-at-hyper** [comment]
Oops, sorry... :)

**Comment by 3lvis** [comment]
@attila-at-hyper Awesome job!

**Pull request merged**
