### PR TITLE
Add basic Swift style guideline

### PR DESCRIPTION
**Pull request by 3lvis**
The idea is to start something, might be better if discussions are followed in different issues/pull requests.

### CODE REVIEW

**Comment by zenangst** [comment]
:star2:

**Comment by kostiakoval** [comment]
I've made a new branch for it :D we think similar

**Comment by jgorset** [comment]
Nice! Where did we get this from?

**Comment by kostiakoval** [comment]
@jgorset what that question to me? 
it's here. https://github.com/hyperoslo/iOS-playbook/tree/swift-style
I just started to write down some issues I see when do PR reviews

**Comment by 3lvis** [comment]
@jgorset https://github.com/hyperoslo/iOS-playbook/blob/master/style-guidelines/Swift.md#attribution :)

**Pull request merged**
