### PR TITLE
Update COMPONENTS.md

### PR DESCRIPTION
**Pull request by attila-at-hyper**
Add explanation about how to test the pod in another project.

### CODE REVIEW

**Comment by attila-at-hyper** [comment]
I've just found a probably better way to co-develop a pod and the project using the pod: the `:path` option in the Podfile. Shouldn't that option be mentioned?

**Comment by attila-at-hyper** [comment]
...then the pod will show up (and be editable) under `Development Pods` of your `Pods` project in the target project. Pretty handy for initial development...

**Comment by NSElvis** [comment]
@attila-at-hyper I think the best way is to drag the files, otherwise you have to run `pod install` one too many times.

**Comment by attila-at-hyper** [comment]
Actually I've tried `path:` and it works very well at this initial development stage (no need to run `pod install`; can edit pod files in place and test the whole thing just as it was a single project).

**Comment by NSElvis** [comment]
I don't like that makes your project more complex when not needed.

You end up working on a workspace, when you don't have any dependencies.

**Comment by NSElvis** [comment]
We've been using it in Form, https://github.com/hyperoslo/Form/blob/master/Demos/Basic-ObjC/Podfile

It hasn't been nice :(

**Comment by attila-at-hyper** [comment]
What was wrong with that? So far it's quite perfect for me: I've setup the Podfile just like in the "final" version (except that I have an extra parameter). I can edit the pod's source in the workspace of the target project (namely Nokkeltall) and once I'm done, I just commit the pod and remove or change `:path`. No need for `pod install`, no need to copy files over and over again. Sorry, but I usually like to understand "why"...

**Pull request merged**
