### PR TITLE
Swift as the preferred language for new components

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by zenangst** [comment]
This goes without saying!

**Comment by fespinoza** [comment]
:+1:

**Comment by 3lvis** [comment]
Feedback needed: 0

**Comment by zenangst** [comment]
:pill:

**Comment by 3lvis** [comment]
:red_circle: :tongue: :red_circle:

**Comment by kostiakoval** [comment]
It means no REMA anymore :tada: :tada: :dancers:

**Comment by 3lvis** [comment]
@kostiakoval what do you mean?! Of course we can do Swift components and use them in Objective-C

**Comment by kostiakoval** [comment]
I mean no more class prefixes

**Comment by 3lvis** [comment]
@kostiakoval Oh that!

FINALLLYYYYYYYY

**Pull request merged**
